### ISSUE TITLE
pay it forward starting at craftsman level

### ISSUE THREAD

**Issue by vleet** [PillarTechnology/guild-docs#12]
I think Apprentices & Journeyman should show community participation

**Comment by jameskbride** [comment]
I don't necessarily disagree with this, but saying that means that the vast majority of Pillarites who are Apprentice and Journeymen right now get bumped to Pre-Apprentice, as there isn't a high degree of community participation right now.

**Comment by vleet** [comment]
Maybe there is a better way to word it.  Some things do not need to be done after hours. They can attend lightning talks, lunch and learns, use slack/chatter, etc.

**Comment by jgartee** [comment]
I agree with community participation.  However, Pillar needs to provide time for this as well.  I have long advocated sharing the cost by opening up Friday afternoons for teaming on an open source project, blogging, or preparing/practicing for upcoming presentations. (I like Fridays because I can stay later or leak over into the weekend, should I so choose ...  my personal bit of "skin in the game"). 

I don't think Pillar needs to eat the entire thing, but it needs to _share_ in the cost and commitment.  Where we invest our personal, professional, and corporate resources shows what we deem to be important.

Such an approach needs to be contrasted to our business model and whether Pillar can afford to invest 10% of their billable hours in employee growth.  I do not know the answer to that.  

I also haven't worked through the client impact of such a commitment, but I'm guessing they wouldn't all be thrilled to see their Pillar staff disappear after lunch on Fridays. :smile:

One must work these things out.

**Comment by blilley** [comment]
I agree with @jgartee 110%

**Comment by mcibulskis** [comment]
While we do appreciate that Pillar not only values our professional development, but encourages it, the responsibility for furthering our own professional development lies squarely on ourselves. 

**It is not our employer's responsibility for ensuring that we further our own professional development -- it is ours and ours alone.**

That we get help from Pillar in doing this (mentoring support, career retros, expenses for learning, etc.) is awesome and is a huge bonus.  It is not something that Pillar is required to do and not something that we should expect Pillar to do for us.

**Comment by JeffHoover** [comment]
While I agree with @mcibulskis that we individually own our personal growth, Pillar aspires to balance  Client / Pillar / People and we work to provide "customer delight". Given this, I would hope that Pillar aspires to "employee delight" as well, and that employees *should* be able to expect Pillar to do more than what "Pillar is required to do". I am not suggesting that Pillar should do anything about development "for us" - I am suggesting that Pillar actively partner with us. Doing so in a way that balances cost strengthens the Pillar and Client portions of the triangle too.

**Comment by jfolkerth** [comment]
I do agree that we need to be responsible for our own professional development. However, I am uncomfortable with my promotion qualifications being heavily tied to activities which occur outside of work. To me that both violates the work/life separation and creates the potential for silent overtime.
