### ISSUE TITLE
# of production releases

### ISSUE THREAD

**Issue by vleet** [PillarTechnology/guild-docs#14]
I like the idea of requiring a number of clients to demonstrate the ability to work in a variety of environments.

Should there be a requirement of a number of production releases?  Seem like the amount of value delivered is also an indication of experience

**Comment by jgartee** [comment]
I would hesitate to put too much emphasis on things that are completely out of the person's control.  Production releases are not controlled by an apprentice or even journeyman.  I like the idea, but am unsure of how it could be fairly implemented.  Maybe as an _optional_ criteria?

**Comment by vleet** [comment]
I think the number of projects and the number of releases are similar that people do not have full control, but they are important for a person to have the experience they need to perform at the next level.

**Comment by mcibulskis** [comment]
@vleet I think that if there are particular types of experiences or knowledge that we want them to have gained from having gone through a number of projects and/or releases, then we should call that out instead of calling out an arbitrary number, from which they may or may not have learned what we are looking for.

**Comment by blilley** [comment]
I agree with @mcibulskis and @jgartee 100%.

If we are going to require a specific number of projects, clients and releases. Then we need to do a better job of rotating people through "projects". 
We need to do a better job of managing clients when we need to rotate people.
We need to make sure that the clients we take on will have a release while we have our people there. Meaning many releases a year.

**Comment by vleet** [comment]
@blilley I agree with your comment.

For a second lets set aside what is possible (or what we are good at providing today)

If someone is going to be great at what they do... what experience would they demonstrate along the way?  Is this an experience that is truly needed?  If it is then we need to find a way to provide that environment.

Do we need to add a value story for Pillar that says something like... 
As Pillar we need to find a way to improve rotation, release frequency, and client expectations so that our people can grow and learn.

**Comment by butlersrepos** [comment]
Agreeing with @jgartee @mcibulskis @blilley. I understand we want to use abstractions instead of hard numbers for these persona attributes but this abstraction seems to only be hiding other abstractions as @mcibulskis said. 

So what are those experiences we think that the process of dealing with production releases grants that are desirable in a craftsman?

**Comment by vleet** [comment]
-The ability to break work into small enough slices to go to production often.
-The ability to understand the overhead getting something delivered and the value of automation to smooth the process
-The ability to consult clients on the value of delivering early and often
