### ISSUE TITLE
Years of Exp, Mentoring, Number of Clients, Engineering Practices

### ISSUE THREAD

**Issue by jameskbride** [PillarTechnology/guild-docs#21]
OK, so I was trying to go Socratic here and start the conversation with questions, but after a brief kick in the rear and a realization that that isn't my style I'm going to be more direct and just start stating opinions.  Please, feel free to respond in kind.  

*This is your captain speaking; please fasten your seat belts and secure all baggage at this time....*

Years of Experience
===================
I have a hard time understanding why years of experience could be construed as a major determining factor regarding where you fall in the roles.  

Many of us have seen first hand that just because you have N number of years of experience doesn't mean you actually learned anything in those years, or that you know what you're talking about (look at many of the client developers we work with who have been with Client X for years and how ineffective they are).  

Conversely we've also seen that the opposite is not true either, that just because you have less than N number of years of experience doesn't mean that you don't know what you're doing.  We have many developers who only have about 3 years of experience who I would certainly qualify as Journeymen.  They've been through the fire, they learned our practices (engineering, team, etc), and they are developers we trust to do the right thing.

**I especially hope we're not planning on looking at years of experience in Pillar as a determinant**.  If this were the case then almost no one is a Craftsman, including individuals we've deemed to be a Craftsman already, such as @mholtman.  Furthermore, if we say that years of experience at Pillar is what we mean then we are essentially making the statement that we don't care about your experience outside of our organization, which is about as myopic as you can get, especially considering that when we hire we (in part) do so by looking at your previous experience.  I hope this is not the case, as there are plenty of developers outside of Pillar that I respect and consider peers.

Number of Clients
=================
Again, I have a hard time understanding why the number of clients could be construed as a major determining factor regarding where you fall in the roles.  

Very often developers don't have a choice about what client they're going to be working with, and many developers have been at the same client on different projects over the years.  Think of all the developers who were at Deere over the last 3-4 years.  Do they not qualify at least as Journeymen simply because they've only ever been at Deere, despite the fact that they might've moved around to muliple projects in that time (GSix to OBA/Seeding/Platform Support, etc)?  Same thing for everyone who has been stuck down at the Gap on various projects, or any other client for an extended period of time.

Rather than number of clients, maybe we consider the number of projects an individual has been on.  Cases in point: @jfpdazey and @donabney.  Both of these individuals worked for Nationwide for years on various projects, and neither of them have been at "6+ clients" (Don and Dazey, please correct me if I'm off).  Despite this I would consider both of them craftsmen, and they have the where-withall to show it. 

Mentoring
=========
I'm going to be blunt: Our mentorship program was/is DOA.  It never had the organizational support it needed to actually mature into something useful.  Yes, there have been mentors/mentorees, and there have even been mentoring sessions that occurred, but I challenge you to point to a single instance of ongoing mentorship, or to point to where Pillar as an organization made this a priority.  We just haven't made the time or effort to make this a successful endevour.  Do I believe it needs to happen?  Absolutely.  Do I think it should be a criteria for placing individuals in the Craftsman level or above in our current state with the current criteria?  Absolutely not.

If we want to change this and make it a requirement for future growth then I'm all for that, but I think that we should prioritize this activity and give it the full support that it needs to be effective.

Engineering Practices
=====================
OK, here we go.  First, I feel I should say that you all know how much I value our engineering practices, and I'm one of the biggest advocates for them.  You'll see me on the fighting on the front lines for them at every chance I get, and if I'm ever not there I hope it is because there is something that is physically keeping me from writing code.  That being said....

**I don't believe that you should have to live and breath our engineering practices to get in the door as a Craftsman.** 

Yes, I just went there.  

The fact of the matter is that the vast majority of developers in the industry simply don't have these skills.  As much as I fight for it TDD is absolutely not the prevalant practice that we believe it should be.  Now, having said that I definitely believe that after a probationary period you had better live, breath, eat, sleep and dream about our practices.  Case in point: @ben-- . Ben is an insanely talented developer with an extensive background.  He is also someone we've deemed to be a Craftsman, but coming in the door he was not a TDD practitioner.  It wasn't until he was with Pillar that he started picking up these skills (@ben-- correct me if I'm wrong).  Given the criteria we've stated he would never have been hired in without the TDD aspect of it.  

I would rather see us hire talented individuals who may not meet all of our (extremely demanding) criteria with the understanding that after a given probationary period that they understand and use our engineering practices, as well as show the benefit of them to our clients.

This doesn't mean that we should loosen our standards, but excluding the vast majority of developers in the community out of hand doesn't lend itself to growth opportunities in terms of hiring talented developers.  My personal opinion is that we need to accept the fact that we need to invest in our people, and that there might be some upfront costs in terms of getting new developers up to speed in our engineering practices.

-------------------------------------------------------

I've said a lot here, and I didn't pull any punches.  If I've offended anyone or stepped on your toes, mea culpa.  Pillar is the single best place I've ever worked at, and I feel privileged and honored to work with all of the genius-level, creative, fun, and caring individuals who make up this organization.  If I've come across strongly here it is because I'm so passionate about what we've got here, and make no mistake, what we've got here is something incredible.  Lets keep making it incredible.  Please consider what I've said here and lets continue the conversation.

Thank you,

Jim Kirkbride

**Comment by CGreff** [comment]
A firm +1 from me.

You've touched on, I think, every topic that I wanted to talk about and said it better than me before I got the chance to, so I'll piggyback here instead. 

With regard to 'Years of Experience' and 'Number of Clients' I especially agree with everything you've said. I think that requirements like this come from the inability to easily qualify what it is you're *actually* looking for. Are we actually asking ourselves, "What is the difference between someone with 2 years of experience and someone with 1? Is there something special that happens in someone's brain on the 366th day (excepting leap years) of working on X? What is the intrinsic quality of an employee who has been on 3 clients that we value more than someone who has had 2?"

In every instance where I've asked about requirements of this sort - and admittedly there aren't very many - I haven't been in this game for nearly as long as many of my peers here :) - I'm always reassured that it's a "loose" requirement and that exceptions are made for the right people. I believe that people are sincere when they say that. However - I'm not convinced that that's all of it. Those requirements can be used, often by well-intentioned people, to justify not promoting/recognizing someone who *has* met all of the other requirements and is by all rights qualified to hold the position for reasons that are outside of that person's control. Whether there are budgetary constraints, or if a company wants to avoid conversations like, "Well you promoted X, and he didn't meet the years requirement, so why don't I deserve a promotion as well?", or whatever other reasons one might imagine. It's not unreasonable that such requirements are deliberately used to be able to dangle promotions over employees' heads - it's the carrot on the stick principle for worker motivation.

I think we need to take the time to think about the intent behind such requirements and what they say about the culture of our company. It's a lot more difficult to explain the qualities you're really looking for in a person when you're describing how much 'experience' they have. That shouldn't prevent us from trying to do so. You've said as much already, but put another way: not all experience is equal. Quantifying years as some standardized metric for how much a person is capable of does nothing for anyone except the people who skirt by the years doing the bare minimum.

Thanks for your thoughts on this Jim!

**Comment by mcibulskis** [comment]
*Disclaimer: This is my two-cents and is not necessarily representative of anyone's point-of-view except my own.  Take what I say with a grain of salt.*

I'd like to start off by saying that I strongly agree with pretty much everything that @jameskbride has said on the topic, but have some things I'd like to add.

# What Are We Actually Trying to Create?
I think it's critical that we understand what we're trying to create with the descriptions of these personas.  The value stories attempt to get this information across, but I think they only tell half the story (what are we trying to create).

### We are trying to create:
  * A set of guiding concepts that point people in the right direction on their career path
  * A generalized description of what the typical expected skills, knowledge, abilities, and responsibilities are for each persona
  * A way to help ensure a good balance in team composition
  * A way to help ensure that we're growing the organization in a scalable fashion (ties into knowing how to better
    balance the composition of teams)

### We are *NOT* trying to create:
  * An exhaustive checklist of items to blindly walk through that describe what is required to "move up to the next level"
  * An exhaustive description of everything that a persona does/not do
  * An exhaustive list of the responsibilities for a persona
  * An exhaustive anything about anything for a persona

### The Personas Are Similar to Learning Stages
If your immediate reaction to this heading is, "Why would I care about this?"  Then feel free to skip this section. :)

For those who are familiar with learning theory, I like to think of the personas as, in some ways, running parallel to learning stages.  (Forgive me if I've taken liberties with the Step It Up learning stages and their names.  Or, feel free to correct me on it, that's cool too.  I added in Maslow's learning stages for additional context.)

Persona | SIU Learning Stage | Maslow's Learning Stage | Other Notes
------- | ------------------ | ----------------------- | -----------
Pre-Apprentice | -- | Unconscious Incompetence | Identified as Ready to Start Learning
Apprentice | Aware | Conscious Incompetence |
Journeyman | Assimilating | Conscious Competence |
Craftsman | Teaching | Unconscious Competence |
Master Craftsman | -- | -- | Leading / Guiding / Setting the Direction

As a side note, learning *never, ever* stops. :)

# Years of Experience and Number of Clients
In all of the interviews I've done over the years, the only thing I've ever found years of experience good for is as a *very* rough gauge of what my expectations should be of their maturity (of their skills/knowledge) and professionalism.  However, I have found it to be reasonably well correlated with their salary expectations.  In other words, historically, it's not been well correlated with what I'm truly interested in knowing about them.

Quantifying the number of clients will also be susceptible to the same problems.  It could be useful as a *very* rough gauge of what my expectations should be of their ability to deal with different situations on a client site, to interact with clients, to help navigate client politics, to help make client employees successful, etc.  But, it won't be well correlated with their ability/knowledge for these skills.

Now, one could argue that, because we have a good interview process in which we're able to weed out almost all of the chaff (we're not perfect, but we do a pretty darn good job), the correlation between the amount of time spent doing something and their related skills/abilities/knowledge should be stronger.  While that might be true, we will still have outliers.  In fact, since we try (and so often succeed) at always hiring the best of the best, I'd argue that we'll tend to have even more of the outliers (at the far right end of the bell curve) who will display a more advanced level of aptitude relative to the length of time or number of clients they've been at, along with a larger standard deviation because we're at the far right end of the bell curve.

We should neither be stating that a person is expected to have (or have on average) a certain number of years of experience nor be stating that they have worked at a particular number of clients.  I agree with @CGreff that what we should be doing is describing what qualities, skills, abilities, and experience we believe to be associated with those years of experience or number of clients and capture that in the description of the personas.  (This honestly should go for anything that we're trying to quantify in these descriptions.)  We have a bit of that in the current persona descriptions, but it feels like there are important things (that are quite useful in guiding people's careers) that we are hiding behind "years of experience" or "number of clients" and should be able to describe in a better way.

# Mentoring
I hope I'm correct assuming that the mentoring referenced in the personas is referring to mentoring in general and not specifically to any kind of formal mentoring program.  I do hope that we can successfully create a more formal supporting mechanism for facilitating finding mentors, because it will be useful.  But, its use (the formal supporting mechanism for facilitating finding mentors or any formal mentoring program) should not be directly tied to the definitions of the personas.

# Engineering Practices
This is the one place where I somewhat disagree with @jameskbride.  Craftsmen will be depended upon to be technical anchors on the teams.  As such, they're going to be the ones helping to uplift the rest of the team.  If they're not yet there with their engineering practices, then they're not ready to take on that persona and maybe they should spend a bit of time in the Journeyman persona until they're ready to be that technical anchor for engineering practices on the team.  It might not take them very long to get up to the point where they can be a technical anchor for engineering practices, but we need them there before we can have them play that persona.

In the past, we've had the benefit of being a bit more Craftsman-heavy on our teams.  I can think of a few teams that I'd been on that had two, three, or even four Craftsman-level people on them.  But Pillar was much leaner at that time and we simply can't find that many Craftsman-level people and sustain our current rate of growth (there are only so many Craftsman-level people in a given city).  So, we need to grow our own Craftsmen.  That means that our teams are going to be much more Journeyman-heavy. We have started (and it will become more prevalent) to have only a single Craftsman on the team (scaling with team size).  This means that we're going to be expecting a fair bit more out of our Craftsmen than we have in the past.

What was once a load that could be shared by multiple Craftsmen on a team will now be initially carried by a single Craftsman.  It'll be up to that Craftsman to quickly start to uplift some members of their team to the point where they can then share the responsibility for uplifting the team as a whole.  Those people won't necessarily be able to technically anchor the engineering practices for an entire team yet (i.e. they're not Craftsmen yet), but they will be stronger Journeymen who can assist in uplifting the rest of the team.  If their engineering practices aren't at a place where they can anchor and bootstrap that uplift on a team, then we need to spend more time growing them so that they can do that (i.e. they need to spend a bit more time as a Journeyman until they're ready to take on the Craftsman persona).

**Comment by vleet** [comment]
I agree that arbitrary #s of clients, years, production releases are problematic and do not get to the root of what we are trying to achieve / describe...

We want people with 
- great situational awareness
- strong consulting & communication skills
- high emotional intelligence

And people that are true Polyglots

To get this you need to ...
- solve a number of challenges
- with a variety of constraints, cultures, people, etc
- etc.

Maybe this type of list could be used

**Comment by jfolkerth** [comment]
Specifically regarding mentoring, as it is currently worded the craftsman/master craftsman personas fall into the trap of hard-coded numbers and are reliant on Pillar recruiting people of a particular level of experience and skill. On the topic of hard-coded numbers I will point people to the other threads on years of experience and number of clients as to why these are in general less helpful (or you can scroll up and read the original post in this thread) and won't repeat the points again.

Since the mentoring requirement is specifically aimed at helping along Apprentices and Journeyman, that requires there to be people of those experience levels available for mentoring. My general impression backed up by a quick keyword search of the company directory is that Pillar is a top heavy organization (many craftsmen and master craftsmen, few apprentices and journeymen). Unless the mentorship requirement is more about instances of mentorship rather than developing an ongoing relationship, which seems contrary to how mentorship has been spoken of at the retros and is less useful, that requirement is not sustainable. Alternatively, you'd have the lower titled personas mentored by about 3 people each, which seems unlikely to be sustainable as well due to the requirements of time and logistics for all parties. Add to that the phrase "references required" and this introduces a level of politics that I'm not interested in seeing as part of either a mentoring/peer relationship or as part of a promotion process. 

Instead, I'd recommend a behavioral qualification that speaks to the person's willingness to teach new skills to others regardless of their rank and act as a more traditional mentor when the opportunity is present. It's one thing to say "you mentored 3 people this year, you get to still be a craftsman" and another to say "you really helped this person grow by guiding them to better practices." The second I think gets closer to what the requirement actually wants from craftsmen and master craftsmen.

On a related note, the per year requirement strongly implies that this is an ongoing evaluation, and while I support measures to prevent the organization from getting stagnant I'm worried this could transform into a lack of compassion in cases where outside circumstances have prevented others from participating to their normal extent. For a commonly occurring and positive example, I would expect new parents to be much less involved with some of the activities required for promotion than single individuals.
