### ISSUE TITLE
Are requirements tied to badges and / or microdegrees in StepItUp?

### ISSUE THREAD

**Issue by mholtman** [PillarTechnology/guild-docs#24]
If not, should they be?

(This question was originally submitted by Bob)

**Comment by jhalburPillar** [comment]
:+1:

**Comment by phasebash** [comment]
If so, can we get someone with an education background to help us ensure that our questions are valid and that our training materials are effective?

**Comment by mcibulskis** [comment]
I don't think that personas should be explicitly tied to microdegrees/badges in SIU.  If we do that, then we're falling into the trap of trying to exhaustively list out every last little thing for every persona, instead of providing directionally correct information that is detailed enough to be useful in helping people to progress in their career and learning.  (see my comment in https://github.com/PillarTechnology/guild-docs/issues/21)

**Comment by JeffHoover** [comment]
@phasebash - I believe Mary Kauffmann is qualified to fulfill that role.

**Comment by jgartee** [comment]
I agree with @mcibulskis.  Remember Microsoft's paper certifications?  I don't dispute the usefulness of StepItUp as _one_ source of enrichment, but I also heavily use PluralSight, blogs, books, and lean on my Pillar peers to bring more depth to my understanding.  In my opinion, carefully thought-out peer review and actual deliveries are still the best measure of a person's readiness to move from one stage to the next.

**Comment by jrsleo** [comment]
If we tie these requirements into StepItUp then we'll need to make sure we actively manage that content and it stays relevant. It might make more sense for Journeyman or maybe Craftsman to have a more formal badge requirement but I would put it on there as a demonstrating checklist rather than the usual videos. If we did this, I would probably structure as follows:

Apprentice: 
- Usual videos and onboarding that everyone must take. Make an Apprentice Microdegree that contains everything we think a person at Pillar should know. 

Journeyman:
- If we feel like there are more videos that an Apprentice does not need to know then create a microdegree. Otherwise I would just have one badge that has a demonstrating tab that has a checklist of the things we want a person to do. Then they can submit the badge for approval when they feel they are ready to go to the next level and we can tie that into some formal process that is handled outside of StepItUp.

Craftsman:
- Same as Journeyman with a checklist but different items. 

Mastercraftsman:
- Another checklist to get to this level. 

We could use StepItUp as a formal starting point for those seeking to reach the next level. There might be other things they need to do but having them fill out what is essentially their CV to prove they meet at least some requirements would help people understand what they need to do to reach the next level and provide the written documentation ahead of time.

My argument is that we should use StepItUp heavily for Apprentice and Journeyman and then slowly withdraw once people move up but still use it as a guideline that people can look at. StepItUp would still only be a starting point for everyone though - the process should still be completed outside of it.
