### ISSUE TITLE
recommended reading list

### ISSUE THREAD

**Issue by mholtman** [PillarTechnology/guild-docs#26]
Would like to capture a list of reading material

**Comment by rdammkoehler** [comment]
Here is a start, left over from the John Deere EAIMS Transformation; https://docs.google.com/a/pillartechnology.com/spreadsheets/d/1c9Z4DD6XyEtQLhINJYxqJiMSySPP4O3IpQD2QCCKsRU/edit?usp=sharing

Let me know if you cannot for some reason read this.

**Comment by phasebash** [comment]
@mholtman Can you provide some guidance on what this reading list should help us accomplish?  Are we looking for reads to support technical proficiency, soft skills, process improvement/tools, or maybe also things from other disciplines?  If yes to all these, then this is a rather long reading list, so then what value does it provide?

**Comment by vleet** [comment]
Here are a few on my list:
The Goal
The Future of Management
Agile Adoption Patterns

**Comment by jgartee** [comment]
I liked these (again, just a few from my library):
How Google Tests Software
Soft Skills
Patterns, Principles, and Practices of Domain-Driven Design
and a bunch of titles from the @rdammkoehler list

**Comment by jgartee** [comment]
@phasebash , the value for me has been that doing a lot of reading and thinking about the takeaways gives me a lot of the distilled wisdom of others.  It jump starts us on the path to having a much broader perspective than we can reasonably gain through our own experience.  Just my 2 cents.

**Comment by phasebash** [comment]
@jgartee I agree completely, it only seems that by building a list we'll end up with a 1000 item list, which isn't much better than any list at all.  Not to mention in a year's time there will be new publications, and a large portion of the reading list will become obsolete.

Sure, there are a few timeless reads, those are the few I believe we should capture.  Beyond that, I believe we should instead be collecting sources of information, not necessarily books themselves.

Google's research publications are a great source of information:
http://research.google.com/pubs/papers.html

**Comment by mcibulskis** [comment]
I think something important to include with a reading list is what we suggest people take away from each of the books on the list.  We're not going to be interested in taking everything as gospel from every book.  There will be books on that list that disagree with each other on various points.  There may be books on the list that are complete garbage with the exception of one or two chapters, which are absolutely brilliant.

Rather than just tell people to "read those books", let's say instead to, "read these books with the intent of taking away these specific concepts and ideas from them (and ignore some of these other ones for the following reasons)."

**Comment by jfolkerth** [comment]
To build on these points, such a reading list should also have a guide for what kind of experience level is right for the book. I wouldn't recommend an Apprentice start trying to learn about good coding practices with the Gang of Four design patterns book. On the flip side, I wouldn't recommend Joshua Bloch's Essential Java to a Craftsmen or Master Craftsmen.

Reinforcing the point of "just because it's written in a book doesn't make it gospel," I'd suggest collecting reviews from various Artisans to get a spectrum of opinions on what is useful and what is less than perfect. I had an excellent example of why this is necessary from a previous reading group, where we got into a rousing discussion of checked vs unchecked exceptions because the author called the issue resolved. As the discussion showed, it was very much not. And especially when those opinions come from highly regarded members of the industry (Uncle Bob, I'm looking at you!) it can be an easy trap for the unwary reader to fall into.
