### ISSUE TITLE
Clarify the so that part of each role...

### ISSUE THREAD

**Issue by vleet** [PillarTechnology/guild-docs#29]
Are the items what you should do to perform at a given level or things to do "so that you can get to the next level"?

To become a craftsmen should I already be doing some of the items on the list?

Is the so that you can make a valuable contribution to your team?  OR so that we can build great things with powerful teams?

**Comment by blilley** [comment]
@vleet Maybe it has changed since you posted,
but from what I am reading the lists are what you should be doing to go to the next level.

To become a Craftsman you should be doing the items in the Journeyman list.

**Comment by vleet** [comment]
@blilley I agree that is what it says but that is the opposite of what we  have said historically.

In the past we have said, demonstrate the items of the next level and then you will be that level... @ddaugher @DonAbney @rdammkoehler is this a purposeful change/distinction?

**Comment by jgartee** [comment]
@vleet, @blilley I would have to agree with the current (stated?) philosophy.  In other words, you have to be _doing_ the job to _get_ the job.  Maybe we should be saying, _To be a Journeyman_... instead of saying _As a Journeyman_...

This also has implications for the Craftsman (in fact, everybody) on the team...if you want to move/advance, you'd best prepare one or two of your "juniors" (hate that word) to actually be doing your job while you're there.  Again, although it sounds trite, a critical responsibility is to train your replacement.  It helps you, it helps them, it helps the client, and it helps the team...ultimately helping Pillar.

By the way, it also justifies, encourages, and requires support of good mentoring practices.

Funny how that works :smile:

**Comment by mcibulskis** [comment]
+1 @jgartee I agree completely.

I also very much like the "eligible" phrasing and the idea of "this is what I need to be doing if I want to 'move up' to the next persona."  It speaks directly to questions I'm frequently asked about, "What do I need to do to become an X?"

It's slightly different (in a significant way) from saying "behave like a person in role X", because people in role X area already trying to improve what they're doing so that they can become a Y.  This means that if a person simply looks at what someone in role X is doing, then they're seeing behaviors that are part of X, but also behaviors that are part of Y.

I like that this helps bring focus to what they should be working on -- what the next steps on their path are, as opposed to showing them a picture of the end state and saying, "that's what you should be doing, get there by imitating it."
