### ISSUE TITLE
What about depth vs. breadth of experience?

### ISSUE THREAD

**Issue by jgartee** [PillarTechnology/guild-docs#31]
### Going against the grain here.

While Pillar places great emphasis on the desirability of being a polyglot, which I think is just fine so far as it goes, my view is that we neglect the value of depth of knowledge in particular areas.  I think we lose the ability to be thought leaders in our industry by emphasizing one so much over the other.

No one has every told me _not_ to go for depth of knowledge, but it feels to me that our culture encourages being a mile wide and an inch deep and does not _actively_ support/emphasize becoming expert in any particular thing.  Sure, we can do it on our own and I support that concept of self-motivated growth.  However, if Pillar wants to have the _industry/tech stack expert_ arrow in the quiver, we will have to look for ways to encourage and support gaining that knowledge.

We can do a lot on our own, but I don't believe we can do _everything_ on our own.

### How it relates to the Guild

A careful reading of our desired behaviors shows no mention of deep expertise.  Proficiency is _not_ the same thing as being an expert.  

Are we a one-trick pony in this regard?  Do we want to be?  These are not criticisms...they are honest questions.  It may well be a case of "that's not what we do".

So, is the only path to advancement to be a really good generalist?

**Comment by mcibulskis** [comment]
I have always interpreted the way that Pillar uses the term "polyglot" to be different from most of the rest of the industry.  The way that I've always heard it used at Pillar is to imply that someone not only has a breadth of knowledge, but that they also have great depth of knowledge in one (or more) areas, plus (most importantly) the ability to acquire great depth of knowledge in additional areas as needed.

I agree that the rest of industry tends to use "polyglot" almost in the same way that they use "generalist", and that isn't what we want to be growing as part of our culture.  We need to make sure that we not only have a breadth of knowledge, but that we are constantly grooming our ability to dive down deeply (gain "deep expertise", to use @jgartee 's phrasing) into particular technologies when the need arises (or whenever we just become curious and want to explore and learn).

@jgartee I agree that "proficiency" is not the same thing as "being an expert" and agree that it needs to be added in, in some way.  But, I think we should call them out separately, so that we continue to foster and encourage growing both our breadth and our depth of knowledge.

**Comment by mstaffeld** [comment]
@jgartee I agree about the not ever achieving an expert status is detracting. Outside of Pillar when I worked in a position where we sourced vendors to help the business, we went for known experts and knowingly paid a lot more for the expert depth of knowledge. Pillar happens to have resources that are deeply knowledgeable about agile practices, but I personally feel like I do not get to play with the cool technologies and ramp up my skill set in things I think are future ready. We are often playing catch up on the client's adoption curve. (Nature of the business.) Maybe the expertise can be combined as almost a subject matter expert of different areas of expertise. What I mean is that, on teams that I have worked on, someone might know Azure inside and out, someone else might known TeamCity and someone else really OCD about code coverage. Having experts in each of those composable things yields a great team. We need a DI container for teams. :)

**Comment by jgartee** [comment]
@mcibulskis and @mstaffeld, the things I struggle with are related to our corporate culture and how we see ourselves in bringing value to the client.  On one hand, we can be a group of experts that are brought in to implement specific technologies or concepts and deliver a product (deep expertise).  On other other hand, we can be a company that is brought in to jump-start a process that is turned over to the client after we get them well down the path (the transformation aspect and more of a teaching/generalist/polyglot approach).

While not mutually exclusive by any means, do we want to focus more on one or the other?  I would like to hear from some of our sales/marketing/strategy side what our goals are in this regard.  It feels like our Forge approach favors deep expertise while our embedded teams favor our polyglot nature.  Sure, we can do both, but different mechanisms are necessary to support and enhance these slightly different goals.

How does this relate to the topic at hand?  We may need to add behaviors to encourage some of our staff to follow the "deep expertise" path, which could place more emphasis on project/client count, active participation in one or more related open source projects, Pillar-sponsored R&D, speaking engagements, and blogging. In short, they become thought leaders in specific aspects of the industry.  Such folks would also be invaluable to our teams and clients in that they can float in and out of different projects, applying a deft touch to more effectively implement specific technologies -- much to the benefit of the client.  Google does something like this with their testing teams.
